In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score, 
    precision_score, recall_score, f1_score, roc_auc_score,
    roc_curve, precision_recall_curve
)
import xgboost as xgb
# import warnings

import core.constants as c

# warnings.filterwarnings('ignore')

# Set random seed for reproducibility
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

In [2]:
X = pd.read_csv(c.RICKD_BASELINE_X_FILE, index_col=0)
Y = pd.read_csv(c.RICKD_BASELINE_Y_FILE, index_col=0)

print(f"X Dataset shape: {X.shape}")
print(f"X Columns: {list(X.columns)}")
display(X.head())

print(f"Y Dataset shape: {Y.shape}")
print(f"Y Columns: {list(Y.columns)}")
display(Y.head())

X Dataset shape: (1832, 93)
X Columns: ['speed_r', 'age', 'Height', 'Weight', 'YrsRunning', 'NumRaces', 'l_step_width', 'l_stride_rate', 'l_stride_length', 'l_swing_time', 'l_stance_time', 'l_pelvis_peak_drop_angle', 'l_pelvis_drop_excursion', 'l_ankle_df_peak_angle', 'l_ankle_eve_peak_angle', 'l_ankle_eve_percent_stance', 'l_ankle_eve_excursion', 'l_ankle_rot_peak_angle', 'l_ankle_rot_excursion', 'l_knee_flex_peak_angle', 'l_knee_add_peak_angle', 'l_knee_add_excursion', 'l_knee_abd_peak_angle', 'l_knee_abd_excursion', 'l_knee_rot_peak_angle', 'l_knee_rot_excursion', 'l_hip_ext_peak_angle', 'l_hip_add_peak_angle', 'l_hip_add_excursion', 'l_hip_rot_peak_angle', 'l_hip_rot_excursion', 'l_foot_prog_angle', 'l_foot_ang_at_hs', 'l_mhw_exc_from_to', 'l_ankle_eve_peak_vel', 'l_ankle_rot_peak_vel', 'l_knee_abd_peak_vel', 'l_knee_add_peak_vel', 'l_hip_abd_peak_vel', 'l_knee_rot_peak_vel', 'l_hip_rot_peak_vel', 'l_pronation_onset', 'l_pronation_offset', 'l_peak_hip_add_velocity', 'l_peak_pelvic_

,speed_r,age,Height,Weight,YrsRunning,NumRaces,l_step_width,l_stride_rate,l_stride_length,l_swing_time,...,r_peak_hip_add_velocity,r_peak_pelvic_drop_velocity,r_vertical_oscillation,Gender_female,Gender_male,DominantLeg_ambidextrous,DominantLeg_left,DominantLeg_right,Level_competitive,Level_recreational
id,,,,,,,,,,,,,,,,,,,,,
100433_20101005t132240,-2.406926,1.231321,-11.741497,-5.056746,0.578686,-0.393107,-0.307243,0.000986,-2.622528,-0.338913,...,-1.743700,0.239058,-1.935588,False,False,False,False,False,False,True
100434_20101117t132240,-1.095016,1.066816,-11.741497,-5.056746,1.308477,-0.393107,-1.831460,0.886585,-1.458975,-0.466027,...,0.764244,-0.390267,-1.344740,True,False,False,False,False,False,True
100537_20120703t102550,-1.325076,-3.128072,0.097259,-0.179365,-0.568129,-0.393107,-0.037324,-0.643565,-1.241474,-0.084685,...,2.255015,0.604189,-0.284941,True,False,False,False,True,False,True
100560_20120717t103748,-0.215279,-0.413733,0.521293,0.931754,-0.776641,-0.393107,0.677045,-1.610390,0.439240,-1.165155,...,3.526927,-1.746297,1.346349,True,False,False,False,True,False,True
101481_20120717t105021,-0.282875,-0.495986,0.316116,-0.828721,-0.776641,-0.393107,0.104643,-0.746010,-0.016982,-0.148242,...,0.475554,1.000454,0.657459,True,False,False,False,False,False,False


Y Dataset shape: (1832, 13)
Y Columns: ['injury_severity_code', 'injury_severity_value', 'injury_code', 'injury2_code', 'injury_desc', 'injury2_desc', 'injury_name', 'injury2_name', 'injured_joint_code', 'injured_joint2_code', 'injured_side_code', 'injured_side2_code', 'is_injured']


,injury_severity_code,injury_severity_value,injury_code,injury2_code,injury_desc,injury2_desc,injury_name,injury2_name,injured_joint_code,injured_joint2_code,injured_side_code,injured_side2_code,is_injured
id,,,,,,,,,,,,,
100433_20101005t132240,volume_intensity,2.0,pain,no_injury,General sensation of discomfort without speci...,No injury has been diagnosed.,pain,no injury,knee,no_injury,right,right,1
100434_20101117t132240,volume_intensity,2.0,disc_dege,no_injury,Breakdown and gradual loss of spinal disc cush...,No injury has been diagnosed.,disc degeneration,no injury,lumbar_spine,no_injury,bilateral,right,1
100537_20120703t102550,missed_2_workouts,3.0,pain,no_injury,General sensation of discomfort without speci...,No injury has been diagnosed.,pain,no injury,hip_pelvis,no_injury,right,right,1
100560_20120717t103748,no_injury,0.0,no_injury,no_injury,No injury has been diagnosed.,No injury has been diagnosed.,no injury,no injury,no_injury,no_injury,right,right,0
101481_20120717t105021,no_injury,0.0,no_injury,no_injury,No injury has been diagnosed.,No injury has been diagnosed.,no injury,no injury,no_injury,no_injury,no_injury,no_injury,0


In [3]:
y = Y["is_injured"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)

print(f"Training set: {X_train.shape[0]} samples")
print(f"Test set: {X_test.shape[0]} samples")

Training set: 1465 samples
Test set: 367 samples


## 3. Define Model Pipelines with Grid Search

In [4]:
models_config = {
    'Logistic Regression': {
        'pipeline': Pipeline([
            ('classifier', LogisticRegression(random_state=RANDOM_STATE))
        ]),
        'param_grid': {
            'classifier__C': [0.1, 1, 10, 100],
            'classifier__penalty': ['l1', 'l2'],
            'classifier__solver': ['liblinear']
        }
    },
    
    'Random Forest': {
        'pipeline': Pipeline([
            ('classifier', RandomForestClassifier(random_state=RANDOM_STATE))
        ]),
        'param_grid': {
            'classifier__n_estimators': [50, 100, 200],
            'classifier__max_depth': [None, 10, 20, 30],
            'classifier__min_samples_split': [2, 5, 10],
            'classifier__min_samples_leaf': [1, 2, 4]
        }
    },
    
    'XGBoost': {
        'pipeline': Pipeline([
            ('classifier', xgb.XGBClassifier(random_state=RANDOM_STATE, eval_metric='logloss'))
        ]),
        'param_grid': {
            'classifier__n_estimators': [50, 100, 200],
            'classifier__max_depth': [3, 6, 9],
            'classifier__learning_rate': [0.01, 0.1, 0.2],
            'classifier__subsample': [0.8, 0.9, 1.0]
        }
    },
    
    'SVM': {
        'pipeline': Pipeline([
            ('classifier', SVC(random_state=RANDOM_STATE, probability=True))
        ]),
        'param_grid': {
            'classifier__C': [0.1, 1, 10],
            'classifier__kernel': ['rbf', 'linear'],
            'classifier__gamma': ['scale', 'auto', 0.1, 0.01]
        }
    }
}


## 4. Train Models with Grid Search and Cross-Validation

In [5]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
trained_models = {}
results = {}

for model_name, config in models_config.items():
    print(f"\n{'======================'}")
    print(f"Training {model_name}...")
    print(f"\n{'======================'}")
    
    grid_search = GridSearchCV(
        estimator=config['pipeline'],
        param_grid=config['param_grid'],
        cv=cv,
        scoring='f1_weighted',
        n_jobs=-1,  # Use all available cores
        verbose=1
    )
    
    grid_search.fit(X_train, y_train)
    
    trained_models[model_name] = grid_search
    results[model_name] = {
        'best_score': grid_search.best_score_,
        'best_params': grid_search.best_params_,
        'cv_results': grid_search.cv_results_
    }
    
    print(f"Best CV Score: {grid_search.best_score_:.4f}")
    print(f"Best Parameters: {grid_search.best_params_}")
    
    y_pred = grid_search.predict(X_test)
    y_pred_proba = grid_search.predict_proba(X_test)
    
    test_accuracy = accuracy_score(y_test, y_pred)
    test_precision = precision_score(y_test, y_pred, average='weighted')
    test_recall = recall_score(y_test, y_pred, average='weighted')
    test_f1 = f1_score(y_test, y_pred, average='weighted')
    

    test_roc_auc = roc_auc_score(y_test, y_pred_proba[:, 1])
    
    results[model_name].update({
        'test_accuracy': test_accuracy,
        'test_precision': test_precision,
        'test_recall': test_recall,
        'test_f1': test_f1,
        'test_roc_auc': test_roc_auc,
        'y_pred': y_pred,
        'y_pred_proba': y_pred_proba
    })
    
    print(f"Test Accuracy: {test_accuracy:.4f}")
    print(f"Test Precision: {test_precision:.4f}")
    print(f"Test Recall: {test_recall:.4f}")
    print(f"Test F1-Score: {test_f1:.4f}")
    print(f"Test ROC AUC: {test_roc_auc:.4f}")


Training Logistic Regression...

Fitting 5 folds for each of 8 candidates, totalling 40 fits
Best CV Score: 0.7574
Best Parameters: {'classifier__C': 1, 'classifier__penalty': 'l1', 'classifier__solver': 'liblinear'}
Test Accuracy: 0.7766
Test Precision: 0.7793
Test Recall: 0.7766
Test F1-Score: 0.7632
Test ROC AUC: 0.7818

Training Random Forest...

Fitting 5 folds for each of 108 candidates, totalling 540 fits
Best CV Score: 0.7789
Best Parameters: {'classifier__max_depth': 20, 'classifier__min_samples_leaf': 2, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 50}
Test Accuracy: 0.7929
Test Precision: 0.8221
Test Recall: 0.7929
Test F1-Score: 0.7715
Test ROC AUC: 0.7643

Training XGBoost...

Fitting 5 folds for each of 81 candidates, totalling 405 fits


/Users/adrianzapaterreig/Documents/Personal/TFM/rickd-analysis/.venv/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Best CV Score: 0.8041
Best Parameters: {'classifier__learning_rate': 0.2, 'classifier__max_depth': 9, 'classifier__n_estimators': 100, 'classifier__subsample': 0.8}
Test Accuracy: 0.8038
Test Precision: 0.8170
Test Recall: 0.8038
Test F1-Score: 0.7898
Test ROC AUC: 0.7780

Training SVM...

Fitting 5 folds for each of 24 candidates, totalling 120 fits
Best CV Score: 0.7904
Best Parameters: {'classifier__C': 10, 'classifier__gamma': 0.01, 'classifier__kernel': 'rbf'}
Test Accuracy: 0.7847
Test Precision: 0.7812
Test Recall: 0.7847
Test F1-Score: 0.7812
Test ROC AUC: 0.8199


In [6]:
for key, value in results.items():
    print(f"Model: {key}")
    display(value["y_pred_proba"])

Model: Logistic Regression


array([[0.45154525, 0.54845475],
       [0.14641172, 0.85358828],
       [0.42502582, 0.57497418],
       [0.32347983, 0.67652017],
       [0.29764866, 0.70235134],
       [0.42597503, 0.57402497],
       [0.9586167 , 0.0413833 ],
       [0.42276883, 0.57723117],
       [0.98224036, 0.01775964],
       [0.38317096, 0.61682904],
       [0.11968713, 0.88031287],
       [0.44714397, 0.55285603],
       [0.13839874, 0.86160126],
       [0.34910634, 0.65089366],
       [0.22677002, 0.77322998],
       [0.18212628, 0.81787372],
       [0.25705261, 0.74294739],
       [0.12304359, 0.87695641],
       [0.03509111, 0.96490889],
       [0.26908899, 0.73091101],
       [0.08752441, 0.91247559],
       [0.0678855 , 0.9321145 ],
       [0.13604105, 0.86395895],
       [0.28598971, 0.71401029],
       [0.21513684, 0.78486316],
       [0.02666558, 0.97333442],
       [0.43103627, 0.56896373],
       [0.04767343, 0.95232657],
       [0.08328831, 0.91671169],
       [0.50945768, 0.49054232],
       [0.

Model: Random Forest


array([[0.40466667, 0.59533333],
       [0.14533333, 0.85466667],
       [0.19763441, 0.80236559],
       [0.35533333, 0.64466667],
       [0.40930108, 0.59069892],
       [0.38795693, 0.61204307],
       [0.85166667, 0.14833333],
       [0.28904762, 0.71095238],
       [0.55966667, 0.44033333],
       [0.369     , 0.631     ],
       [0.2702    , 0.7298    ],
       [0.40233333, 0.59766667],
       [0.31933333, 0.68066667],
       [0.10666667, 0.89333333],
       [0.21      , 0.79      ],
       [0.18353333, 0.81646667],
       [0.31116667, 0.68883333],
       [0.23333333, 0.76666667],
       [0.23742857, 0.76257143],
       [0.305     , 0.695     ],
       [0.52833333, 0.47166667],
       [0.28918413, 0.71081587],
       [0.415     , 0.585     ],
       [0.21666667, 0.78333333],
       [0.2291236 , 0.7708764 ],
       [0.32      , 0.68      ],
       [0.37      , 0.63      ],
       [0.30619048, 0.69380952],
       [0.172     , 0.828     ],
       [0.34666667, 0.65333333],
       [0.

Model: XGBoost


array([[2.44226456e-02, 9.75577354e-01],
       [6.44344091e-03, 9.93556559e-01],
       [2.16103792e-02, 9.78389621e-01],
       [2.04524636e-01, 7.95475364e-01],
       [1.11893773e-01, 8.88106227e-01],
       [3.47658038e-01, 6.52341962e-01],
       [9.96274948e-01, 3.72504140e-03],
       [6.95072412e-02, 9.30492759e-01],
       [9.55073953e-01, 4.49260771e-02],
       [3.07872891e-01, 6.92127109e-01],
       [7.43863583e-02, 9.25613642e-01],
       [5.15740871e-01, 4.84259129e-01],
       [4.51509356e-02, 9.54849064e-01],
       [5.98472357e-03, 9.94015276e-01],
       [1.71844900e-01, 8.28155100e-01],
       [1.03312075e-01, 8.96687925e-01],
       [4.68837023e-02, 9.53116298e-01],
       [1.15031481e-01, 8.84968519e-01],
       [1.10784769e-02, 9.88921523e-01],
       [1.21657789e-01, 8.78342211e-01],
       [4.05481875e-01, 5.94518125e-01],
       [3.36145759e-02, 9.66385424e-01],
       [8.99446607e-02, 9.10055339e-01],
       [5.15618920e-02, 9.48438108e-01],
       [3.169411

Model: SVM


array([[0.30446062, 0.69553938],
       [0.19835576, 0.80164424],
       [0.31538732, 0.68461268],
       [0.37654962, 0.62345038],
       [0.45787291, 0.54212709],
       [0.66613641, 0.33386359],
       [0.86019956, 0.13980044],
       [0.36523248, 0.63476752],
       [0.6128086 , 0.3871914 ],
       [0.8224476 , 0.1775524 ],
       [0.42736385, 0.57263615],
       [0.30057951, 0.69942049],
       [0.06053481, 0.93946519],
       [0.11174957, 0.88825043],
       [0.1231101 , 0.8768899 ],
       [0.12888509, 0.87111491],
       [0.39159739, 0.60840261],
       [0.20879187, 0.79120813],
       [0.12952265, 0.87047735],
       [0.28413477, 0.71586523],
       [0.09813255, 0.90186745],
       [0.09769284, 0.90230716],
       [0.12398418, 0.87601582],
       [0.10218125, 0.89781875],
       [0.19061831, 0.80938169],
       [0.10595893, 0.89404107],
       [0.24040966, 0.75959034],
       [0.40537074, 0.59462926],
       [0.06632907, 0.93367093],
       [0.48672631, 0.51327369],
       [0.

Podria una linea de TFM ser:
- Partir de estos resultados base y investigar como podemos mejorar las capacidades de predicción?